apiVersion: apps/v1
kind: Deployment
metadata:
  name: luckywebapp
  labels:
    app: luckywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luckywebapp
  template:
    metadata:
      labels:
        app: luckywebapp
    spec:
      containers:
      - name: luckywebapp
        image: luckyregistry11.azurecr.io/luck:v1
        ports:
        - containerPort: 80

